### ISSUE TITLE
Content not displaying correctly on mobile

### ISSUE THREAD

**Issue by rmartinezduque** [chakra-ui/frontity-chakra-ui-theme#1]
**Observed behavior**

I can't see the content correctly when I visit the Chakra theme on mobile unless I scroll horizontally.

I'm using a Xiaomi Mi A1 device and the Chrome browser on mobile.

Here are some screenshots:

![Screenshot_20200127-120328-1](https://user-images.githubusercontent.com/20700757/73174493-31d7ee00-4108-11ea-9ea3-aa9e504fbded.png)
![Screenshot_20200127-120349](https://user-images.githubusercontent.com/20700757/73174495-32708480-4108-11ea-8f08-8c9ee7be81d6.png)
![Screenshot_20200127-130851](https://user-images.githubusercontent.com/20700757/73174496-32708480-4108-11ea-8c70-a9b0c56ad19e.png)

**Comment by segunadebayo** [comment]
Thanks for the issue @rmartinezduque. I'll look into this.

**Comment by segunadebayo** [comment]
I've just resolved this, Reyes. See the attachment below
![Sizzy-iPhone 11 Pro localhost 28Jan 14 08](https://user-images.githubusercontent.com/6916170/73266792-e725a700-41d7-11ea-8f39-9043a58e106c.png)

**Comment by rmartinezduque** [comment]
Awesome, thanks Segun!
