### ISSUE TITLE
First post link only works on top of the image

### ISSUE THREAD

**Issue by luisherranz** [chakra-ui/frontity-chakra-ui-theme#2]
It looks like there's a problem with the link of the first post, it only works when you click on the top section of the image.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/3305402/73175016-233a0880-4101-11ea-8389-0992f147af44.gif)

**Comment by segunadebayo** [comment]
Thank you, Luis. I've just resolved this.
