### ISSUE TITLE
Pagination buttons are disabled

### ISSUE THREAD

**Issue by luisherranz** [chakra-ui/frontity-chakra-ui-theme#3]
If you go to https://frontity-chakra.now.sh/page/2/ you will see that the pagination is disabled for the next and the previous page:
![frontity-chakra now sh_page_2_(Pixel 2)](https://user-images.githubusercontent.com/3305402/73185800-a44fca80-4116-11ea-9330-0cb0537e64f7.png)

By a quick look at the code, it seems like the `isDisabled` attribute should be the opposite of what it is right now:
https://github.com/chakra-ui/frontity-chakra-ui-theme/blob/master/packages/frontity-chakra-theme/src/components/archive/pagination.js#L87-L88

```js
<PrevLink link={nextPageLink} isDisabled={!isTherePreviousPage} />
<NextLink link={prevPageLink} isDisabled={!isThereNextPage} />
```

**Comment by segunadebayo** [comment]
Thanks for this Luis, I'll double-check the code again.

**Comment by segunadebayo** [comment]
I've just fixed this. Thanks for the suggestion, Luis
