### ISSUE TITLE
Issue with menu configuration/pulling page data in

### ISSUE THREAD

**Issue by Trevorton27** [chakra-ui/frontity-chakra-ui-theme#33]
Hello, Really love this theme. Beautiful job! However, I'm having some issues with pulling in page data. I started a conversation [here on the frontity forum](https://community.frontity.org/t/pull-data-from-wordpress-page/4698) but then thought it might be helpful to reach out to you here. I notice the chakra them is running beautifully using the source url https://test.frontity.org so I am not sure what is wrong in my configuration.

**Comment by Trevorton27** [comment]
Ok, nevermind. I fixed it. I think it had to do with the @frontity/wp-source configuration. Awesome!

**Comment by luisherranz** [comment]
Glad to know. Feel free to reopen if there is a real issue after all 🙂
